# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init: echo 'npm install --save-dev hardhat' # runs during prebuild
    command: echo 'npm install --save-dev prettier prettier-plugin-solidity'

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview

vscode:
  extensions:
    - "NomicFoundation.hardhat-solidity"
    - "JuanBlanco.solidity"
    - "vivaxy.vscode-conventional-commits"
    - "styled-components.vscode-styled-components"
    - "esbenp.prettier-vscode"
